### ISSUE TITLE
Pic URL 403Forbidden

### ISSUE THREAD

**Issue by ahaaaaaaaaaa1** [TrustworthyComp/mcfend#2]
![image](https://github.com/TrustworthyComp/mcfend/assets/130056547/2ba74491-9ca8-45c4-b03a-36cdcd9ebad0)

**Comment by TrustworthyComp** [comment]
We apologize for any inconvenience caused. Due to SINA's image storage methods, images cannot be accessed directly via browsers but can be downloaded using the provided code snippets.

```
import os
import pandas as pd
import requests

data = {
    'news_id': [1],
    'pic_url': [
        '//ww1.sinaimg.cn/large/005M4DfQjw1exy3i7zr5hj30bc0bsgly.jpg'
    ]
}

df = pd.DataFrame(data)

# Convert image links and download images
def download_image(url, save_path):
    response = requests.get(url)
    if response.status_code == 200:
        with open(save_path, 'wb') as f:
            f.write(response.content)
        print(f"Downloaded successfully: {url} -> {save_path}")
    else:
        print(f"Download failed: {url}")

# Create folder to save images
output_folder = 'downloaded_images'
os.makedirs(output_folder, exist_ok=True)

# Iterate through each row of DataFrame
for index, row in df.iterrows():
    news_id = row['news_id']
    pic_url = row['pic_url']
    if pic_url:
        full_url = 'http:' + pic_url
        image_name = f"news_{news_id}.jpg"  # Naming the image using news_id
        save_path = os.path.join(output_folder, image_name)
        download_image(full_url, save_path)
    else:
        print(f"Empty link, skipping: Row {index}")

print("Image download completed!")
```

Feel free to let us know if you need any further assistance!

**Comment by TrustworthyComp** [comment]
Hi @ahaaaaaaaaaa1, since this issue should have already been resolved and there are no follow-up problems, we are going to close this issue for now. If there are any follow-up issues, please feel free to reopen this issue or open a new one.

**Comment by ahaaaaaaaaaa1** [comment]
The problem has been solved, thank you very much!

**Comment by morning-l** [comment]
Hello, I have tried the above code and can only save one image file. I would like to obtain the complete image file. Can you provide the address or code?

**Comment by morning-l** [comment]
Hello, I have tried the above code and can only save one image file. I would like to obtain the complete image file. Can you provide the address or code?

**Comment by TrustworthyComp** [comment]
> Hello, I have tried the above code and can only save one image file. I would like to obtain the complete image file. Can you provide the address or code?

Hi! please see https://github.com/TrustworthyComp/mcfend/issues/5#issuecomment-2221962994
