### ISSUE TITLE
About experiments.

### ISSUE THREAD

**Issue by Yasuo-orphan** [TrustworthyComp/mcfend#3]
Your work is great. Also, will the code for experiments using the baseline model be uploaded here?

**Comment by TrustworthyComp** [comment]
Thank you so much for your attention to our work! Our implementation for the baseline models is all based on open-source repositories, such as https://github.com/RMSnow/WWW2021 and https://github.com/cyxanna/CAFE.

**Comment by Yasuo-orphan** [comment]
Oh, great! Thank you
